authors = ["gabrielgellner "]
name = "GabeUtils"
uuid = "322a086e-c657-11e8-2137-c1af6f48e1a1"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
